import './globals.css'
import { Footer } from '../components/Sections'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Dylan P</title>
      </head>
      <body className="flex flex-col">
        {children}
        <Footer />
      </body>
    </html>
  )
}
